driver.switch_to.window(driver.window_handles[0])
driver.switch_to.new_window('tab')
driver.get("about:debugging#addons")
ublockUUID = driver.find_element(By.XPATH, "//dd[text()='leechblockng@proginosko.com']/parent::*/parent::*/div[2]/dd").text
ublockURL = "moz-extension://"+ublockUUID+"/options.html"
driver.get(ublockURL)
WebDriverWait(driver, 10).until(expected_conditions.element_to_be_clickable((By.ID, "tabGeneral")))
driver.find_element(By.ID, "tabGeneral").click()
WebDriverWait(driver, 10).until(expected_conditions.presence_of_element_located((By.ID, "importFile")))
driver.find_element(By.ID, "importFile").send_keys(firefoxProfilePath+"/system-scripts/leechblock-config.txt")
WebDriverWait(driver, 10).until(expected_conditions.element_to_be_clickable((By.ID, "importOptions")))
driver.find_element(By.ID, "importOptions").click()
WebDriverWait(driver, 10).until(expected_conditions.element_to_be_clickable((By.XPATH, "//div[@aria-describedby='alertImportSuccess']/div[3]/div/button")))
driver.find_element(By.XPATH, "//div[@aria-describedby='alertImportSuccess']/div[3]/div/button").click()
WebDriverWait(driver, 10).until(expected_conditions.element_to_be_clickable((By.ID, "saveOptionsClose")))
driver.find_element(By.ID, "saveOptionsClose").click()
WebDriverWait(driver, 10).until(expected_conditions.number_of_windows_to_be(1))
driver.switch_to.window(driver.window_handles[0])
