user_pref("webgl.disabled", false);
user_pref("privacy.resistFingerprinting", false);
user_pref("privacy.clearOnShutdown.offlineApps", false);
user_pref("privacy.sanitize.sanitizeOnShutdown", false);
user_pref("firefoxpwa.allowedDomains", "*.usherbrooke.ca,usherbrooke.ca,*.live.com,live.com,*.microsoftonline.com,microsoftonline.com,*.sharepoint.com,sharepoint.com,*.office365.com,office365.com,*.office.com,office.com,*.microsoft.com,microsoft.com,*.outlook.com,outlook.com,*.microsoft365.com,microsoft365.com,aka.ms");
user_pref("firefoxpwa.displayUrlBar", 2);
user_pref("firefoxpwa.enableTabsMode", true);
user_pref("firefoxpwa.linksTarget", 3);
user_pref("firefoxpwa.openOutOfScopeInDefaultBrowser", true);